password: '{cipher}AQClOfSCII5daNIeofIlaB+nAbq381xKO+z7JSCYfKIO3oTOQak4ljrYml/QUfHyNkjP2ROHAYX6gfdsNsx3XYhSyjRRbUo5kHVAeyYPL15nDvIjmqKBbz07vXQr0TgdrqqFDgsxPGYZPESeyJ4yExFry4OWwNg7PIuXpzLVuJKq+dKeffn5s1kn4SdatL8CGEnpEXReSvOQMkLNNWIclFw93mq0OoQm4d3muSvWl4FECfZZGEyo4sM6bGCW7aASKpxHMO9BKwfLUvMeOqFnO599qZzFBaIyjFowty7bW9jAJAQHSIxVLatfdcxpPcudrLYtT57EvqloB+mvFj0olRtfxq8SdXMl3nBqMZEUC/3Bi2FGiK/4UbOxMn3pXkDTL6o='
orderId: 687
eureka:
  instance:
  instance-id: ${spring.application.name}-${random.int}
logging:
  config: file:///D:/STS Workspace/logback-spring.xml
server:
  port: 8081
spring:
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
